In [2]:
import numpy as np

### 문제1
0이상 100이하의 임의의 정수들로 구성되는 10행 5열의 2차원 numpy array인 ``score``를 생성하시오.

In [3]:
score = np.random.randint(0, 101,size=(10,5))
score

array([[ 98,  67,  25,  56,   9],
       [ 85,  44,  43,  78,  16],
       [ 98,   1,   2,  95,  86],
       [ 92,  92,  99,  39,  36],
       [  6,   6,  83,  92,   0],
       [ 72,  93,  24,  57,  62],
       [  1,   3,  83,  10,  49],
       [ 48,  98,  86,  46, 100],
       [ 51,  59,  63,  20,  38],
       [ 89,  25,  37,  30,  87]])

### 문제2
지금부터 ``score``가 10명의 학생들의 국어, 영어, 수학, 과학, 사회 점수를 뜻한다고 가정하자.

이제 5개 과목의 평균점수를 뜻하는 ``avg_subject`` array(1차원)를 생성하시오. 

In [4]:
avg_subject = np.mean(score, axis=0)
avg_subject

array([64. , 48.8, 54.5, 52.3, 48.3])

### 문제3
학생별 평균점수를 뜻하는 ``avg_student`` array(1차원)를 생성하시오. 

In [5]:
avg_student = np.mean(score, axis=1)
avg_student

array([51. , 53.2, 56.4, 71.6, 37.4, 61.6, 29.2, 75.6, 46.2, 53.6])

### 문제4
10명 중 row의 index가 짝수인 학생은 여학생(index 0 포함), 홀수인 학생은 남학생이라고 할 때, <br>
여학생 전체의 5개과목별 평균점수를 뜻하는 ``avg_female`` array(1차원)을 구하시오.

In [6]:
avg_female = np.mean(score[::2], axis=0)
avg_female

array([50.8, 27.2, 51.2, 54.6, 36.4])

### 문제5
마찬가지로 남학생 전체의 5개과목별 평균점수를 뜻하는 ``avg_male`` array(1차원)을 구하시오.

In [7]:
avg_male = np.mean(score[1::2], axis=0)
avg_male

array([77.2, 70.4, 57.8, 50. , 60.2])

### 문제6
5개 과목의 표준편차 std_array(1차원)를 생성하시오.

In [27]:
std_array = np.std(score, axis=0)
std_array

array([29.45318319, 31.86989175, 24.40676136, 29.97932621, 24.6771149 ])

### 문제7
각 과목의 최고점수(max) max_array(1차원)를 생성하시오.

In [28]:
max_array = np.max(score, axis=0)
max_array

array([ 94,  99, 100,  94,  97])